### ISSUE TITLE
Cannot run locally due to no `./secret.js`

### ISSUE THREAD

**Issue by balupton** [dado3212/iTunesToSpotify#3]
Please provide instructions on how to create this file

```
> npm start

> iTunesToSpotify@1.0.1 start /Users/balupton/Projects/apps/iTunesToSpotify
> electron .

App threw an error during load
Error: Cannot find module './secret.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/Users/balupton/Projects/apps/iTunesToSpotify/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/balupton/Projects/apps/iTunesToSpotify/js/main.js:3:38)
    at Object.<anonymous> (/Users/balupton/Projects/apps/iTunesToSpotify/js/main.js:95:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by dado3212** [comment]
You need to create a file in `js` called secret.js, of the form export { CLIENT_ID = '...', CLIENT_SECRET = '...' } where CLIENT_ID and CLIENT_SECRET are the id/secret of your Spotify application created in developer.spotify.com.  Added a note about it to the README as well!
